  myboot:
    name: Spring
    age: ${random.int(1,100)}

  spring:
    application:
      name: MySpringBoot
    profiles:
      active: test
    datasource:
      url: jdbc:mariadb://127.0.0.1:3307/boot_db
      driver-class-name: org.mariadb.jdbc.Driver
      username: boot
      password: boot
#      url: jdbc:h2:mem:testdb
#      driver-class-name: org.h2.Driver
#      username: sa
    jpa:
      hibernate:
        ddl-auto: create
      show-sql: true

---
  spring:
    profiles: test
  myboot:
    fullName: ${myboot.name} Boot DEV Mode
  logging:
    level:
      com.base.myspringboot: DEBUG
---
  spring:
    profiles: prod
  myboot:
    fullName: ${myboot.name} Boot PROD Mode
  logging:
    level:
      com.base.myspringboot: INFO